### ISSUE TITLE
Project 09 PhotoScroll 

### ISSUE THREAD

**Issue by gogozs** [soapyigu/Swift30Projects#15]
`contentInset` not set correctly when tap textField more than once.

**Comment by soapyigu** [comment]
Thank you for letting me know, will study it ASAP

**Comment by soapyigu** [comment]
Hi could you please give me more details for this bug? I can't reproduce it.

**Comment by gogozs** [comment]
tap the textField, dismiss the keyboard, do it twice.

**Comment by soapyigu** [comment]
I can't reproduce the bug, could you please send an email to me with a gif to demo the bug? Thank you in advance.
