### ISSUE TITLE
Readme Typo

### ISSUE THREAD

**Issue by NicoHinderling** [soapyigu/Swift30Projects#16]
Hi Yi! I know this is minor but I thought I might as well point it out: [This title](https://github.com/soapyigu/Swift30Projects#whatss-next) has an extra 's' (Should be "What's Next"). No PR because this is so tiny 😛 

Thanks for making this project, it's been very nice to read through!

**Comment by soapyigu** [comment]
Hi thank you for pointing this out. Already fixed.
