### ISSUE TITLE
Project 07 - PokedexGo tableView:didSelectRowAt: doesn't get called

### ISSUE THREAD

**Issue by vietstone** [soapyigu/Swift30Projects#17]
Hi, 
Your project is really awesome. I'm investigating each of it, now on Project 07.
When I run the project on Xcode 8.3, it seems the function `MasterViewController`.`tableView:didSelectRowAt:` doesn't get called on both iPhone and iPad.
Could you take a look? Then I can try to fix if you need my effort. Thank you.

**Comment by soapyigu** [comment]
It was fixed. The issue is due to the overlap between tapGesture to dismissKeyboard and tableView:didSelectRowAt: function. Good catch
