### ISSUE TITLE
about Project 03 - Stopwatch

### ISSUE THREAD

**Issue by azureland** [soapyigu/Swift30Projects#6]
Just found that both timer ( main and lap ) will STOP while scrolling tableview.

i think add timer to runloop with commonModes should fix it.

**Comment by soapyigu** [comment]
yeah, will do that, thank you

**Comment by soapyigu** [comment]
Fixed

**Comment by h01m3s** [comment]
Actually lap timer will still STOP while scrolling tabview after update. Main timer works fine now.
